name: GitHub Deployments
description: GitHub action for working painlessly with deployment statuses.
author: maxgfr
branding:
  icon: bookmark
  color: blue
runs:
  using: node16
  main: dist/index.js

inputs:
  token:
    required: true
    description: GitHub token
  step:
    required: true
    description: One of 'start' and 'finish'
  description:
    required: false
    description: Description to set in status
  ref:
    required: false
    description: The git ref to use for the deploy, defaults to `github.ref`
  env:
    required: false
    description: The name of the deployment environment for Github. It could be an array of string. (Required for `start`, `deactivate-env` and `delete-env`)
  deployment_id:
    required: false
    description: The deployment id to update (if specified during `start`, the deployment will be updated instead of a new one created)
  env_url:
    required: false
    description: The environment URL. It could be an array of string. (For `finish` only)
  status:
    required: false
    description: The deployment status. (For `finish` only)
  log_args:
    required: false
    description: Print arguments used by this action.
