name: 'action-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'
      - name: Notify deployment start
        uses: ./
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          description: 'Deploying environment A and environment B'
          env: '["envA", "envB"]'
          log_args: true
      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'
      - name: Notify deployment deactivation
        uses: ./
        with:
          step: deactivate-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: '["envA", "envB"]'
          log_args: true
      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'
      - name: Notify deployment delete
        uses: ./
        with:
          step: delete-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: '["envA", "envB"]'
          log_args: true
      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'
      - name: Notify deployment start
        uses: ./
        id: deployment2
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          description: 'Deploying environment C and environment D'
          env: '["envC", "envD"]'
          log_args: true
      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'
      - name: Notify deployment finish
        uses: ./
        with:
          step: finish
          status: 'success'
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment_id: ${{ steps.deployment2.outputs.deployment_id }}
          log_args: true
      - name: Extract branch name
        id: get_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | tr / -)"
      - name: start deployment
        uses: bobheadxi/deployments@v1
        id: deploymentX
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: release

      - name: update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: 'success'
          env: ${{ steps.deploymentX.outputs.env }}
          deployment_id: ${{ steps.deploymentX.outputs.deployment_id }}
      - name: mark environment as deactivated
        uses: bobheadxi/deployments@v1
        with:
          step: delete-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: release
          desc: Environment was pruned
